language: python
python:
  - "3.9"
compiler:
  - gcc

install:
  - pip install -U platformio==6.0.2
  
  - wget https://github.com/pallets/click/archive/refs/tags/8.1.3.zip -O /tmp/click-8.1.3.zip
  - unzip /tmp/click-8.1.3.zip -d /tmp/

script:
  - platformio test -e native
