name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++

      - name: Install dependencies
        run: |
          pip install -U platformio
          pip install -U urllib3==1.26.12
          wget https://github.com/pallets/click/archive/refs/tags/8.1.3.zip -O /tmp/click-8.1.3.zip
          unzip /tmp/click-8.1.3.zip -d /tmp/
          cd /tmp/click-8.1.3 && pip install .

      - name: Run tests
        run: platformio test -e native
